rm -f -r Monoscape.Common/bin/*
rm -f -r Monoscape.ApplicationGridController/bin/*
rm -f -r Monoscape.ApplicationGridController.Api/bin/*
rm -f -r Monoscape.CloudController/bin/*
rm -f -r Monoscape.CloudController.Api/bin/*
rm -f -r Monoscape.CloudController.External.Api/bin/*
rm -f -r Monoscape.LoadBalancerController/bin/*
rm -f -r Monoscape.LoadBalancerController.Api/bin/*
rm -f -r Monoscape.LoadBalancerController.Web/bin/*
rm -f -r Monoscape.NodeController/bin/*
rm -f -r Monoscape.NodeController.Api/bin/*
rm -f -r Monoscape.Dashboard/bin/*

rm -f -r Monoscape.Common/obj/*
rm -f -r Monoscape.ApplicationGridController/obj/*
rm -f -r Monoscape.ApplicationGridController.Api/obj/*
rm -f -r Monoscape.CloudController/obj/*
rm -f -r Monoscape.CloudController.Api/obj/*
rm -f -r Monoscape.CloudController.External.Api/obj/*
rm -f -r Monoscape.LoadBalancerController/obj/*
rm -f -r Monoscape.LoadBalancerController.Api/obj/*
rm -f -r Monoscape.LoadBalancerController.Web/obj/*
rm -f -r Monoscape.NodeController/obj/*
rm -f -r Monoscape.NodeController.Api/obj/*
rm -f -r Monoscape.Dashboard/obj/*
