CREATE TABLE [Application] (
[Id] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
[Name] NVARCHAR(1000)  NULL,
[Version] NVARCHAR(200)  NULL,
[FilePath] VARCHAR(2000)  NULL,
[State] NVARCHAR(100)  NULL
);

CREATE TABLE [Tenant] (
[Id] INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
[ApplicationId] INTEGER  NOT NULL,
[Name] NVARCHAR(200)  NULL,
[UpperScaleLimit] INTEGER  NULL,
[ScalingFactor] INTEGER  NULL,
FOREIGN KEY(ApplicationId) REFERENCES Application(Id)
);